# Введение {-#intro}

В настоящее время для написания дипломов, отчетов и научных работ широко используется Microsoft Word (далее MS Word). Следует отметить, что MS Word имеет следующие существенные недостатки:

* форматы doc и docx - бинарные (не текстовые), поэтому сложно сравнивать разные версии документа между собой и искать текст;
* сложно организовать совместную работу;
* сложно автоматизировать нумерацию разделов, рисунков, таблиц, формул, сносок, списка литературы, списка используемых сокращений, иллюстраций, алфавитных указателей в больших документах (книги, дипломы, диссертации);
* не удобно вставлять ссылки на картинки, расположенные в отдельных файлах;
* не удобно вставлять код программ, расположенных в отдельных файлах;
* медленная и ненадежная работа с большими документами;
* формулы сохраняются в MathType (бинарный формат, не позволяет сравнивать версии между собой, только визуально);
* сложность создания и работы с многофайловыми документами (с мастер-документом).

Но MS Word обладает следующими достоинствами:

* широкое распространение программы;
* возможность создать документ практически любой сложности и произвольного формата.

Альтернативами для MS Word могут выступать следующие программы:

* использование бинарных форматов

  - LibreOffice Writer - по смыслу тоже самое, что и MS Word;
  - WPS Office - по смыслу тоже самое, что и MS Word;
  - Google Docs - удобная совместная работа, но нет автоматической нумерации объектов и прочего.

* текстовые форматы

  - LaTeX - отличный язык для подготовки высококачественных документов любого объема и сложности, но имеет слишком перегруженный синтаксис и высокий порог вхождения;
  - Легковесные языки разметки (Lightweight Markup Language) на основе простого текста (plain-text):

    + Markdown - 2004 г. - [http://daringfireball.net/projects/markdown](http://daringfireball.net/projects/markdown);
    + reStructuredText - 2002 г. - [http://docutils.sourceforge.net/rst.html](http://docutils.sourceforge.net/rst.html);
    + AsciiDoc - 2013 г. - [http://asciidoc.org/](http://asciidoc.org/);
    + MediaWiki - 2002 г. - [https://www.mediawiki.org/](https://www.mediawiki.org/);
    + Emacs Org-Mode - 2003 г. - [https://orgmode.org/](https://orgmode.org/).

Настоящий документ подготовлен с помощью легковесного языка разметки Markdown. Рассмотрим использование этого языка более подробно. В последующих главах будут рассмотрены примеры использования Markdown, RMarkdown и bookdown.
